In [815]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session
import warnings
warnings.filterwarnings('ignore')

/kaggle/input/the-indian-movie-database/1950-1989/bollywood_1950-1989.csv
/kaggle/input/the-indian-movie-database/1950-1989/bollywood_text_1950-1989.csv
/kaggle/input/the-indian-movie-database/1950-1989/bollywood_meta_1950-1989.csv
/kaggle/input/the-indian-movie-database/1950-1989/bollywood_ratings_1950-1989.csv
/kaggle/input/the-indian-movie-database/collaborative/ratings.csv
/kaggle/input/the-indian-movie-database/collaborative/genome_tags.csv
/kaggle/input/the-indian-movie-database/collaborative/genome_scores.csv
/kaggle/input/the-indian-movie-database/collaborative/README.txt
/kaggle/input/the-indian-movie-database/collaborative/titles.csv
/kaggle/input/the-indian-movie-database/collaborative/tags.csv
/kaggle/input/the-indian-movie-database/collaborative/links.csv
/kaggle/input/the-indian-movie-database/1950-2019/bollywood_writers_data_1950-2019.csv
/kaggle/input/the-indian-movie-database/1950-2019/bollywood_full_1950-2019.csv
/kaggle/input/the-indian-movie-database/1950-2019/bollywood_crew_1950-2019.csv
/kaggle/input/the-indian-movie-database/1950-2019/bollywood_crew_data_1950-2019.csv
/kaggle/input/the-indian-movie-database/1990-2009/bollywood_ratings_1990-2009.csv
/kaggle/input/the-indian-movie-database/1990-2009/bollywood_text_1990-2009.csv
/kaggle/input/the-indian-movie-database/1990-2009/bollywood_meta_1990-2009.csv
/kaggle/input/the-indian-movie-database/1990-2009/bollywood_1990-2009.csv
/kaggle/input/the-indian-movie-database/2010-2019/bollywood_text_2010-2019.csv
/kaggle/input/the-indian-movie-database/2010-2019/bollywood_ratings_2010-2019.csv
/kaggle/input/the-indian-movie-database/2010-2019/bollywood_2010-2019.csv
/kaggle/input/the-indian-movie-database/2010-2019/bollywood_meta_2010-2019.csv
/kaggle/input/recommendations/movie_1916_2021_Main_dataset.csv
/kaggle/input/bollywood-movie-dataset/BollywoodActorRanking.csv
/kaggle/input/bollywood-movie-dataset/BollywoodDirectorRanking.csv
/kaggle/input/bollywood-movie-dataset/BollywoodMovieDetail.csv

In [842]:
old_df = pd.read_csv('../input/recommendations/movie_1916_2021_Main_dataset.csv')
old_df['actor_4_name'] = 'unknown'
old_df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,combination,actor_4_name
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...,unknown
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...,unknown
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...,unknown
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,unknown
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...,unknown

In [843]:
class BOLLYWOOD_DATASET:
    def load_dataset(self, path, col):
        df = pd.read_csv(path, usecols=col)
        return df
    
    def get_shape(self, df):
        return df.shape
    
    def nanVal(self, df):
        null = df.isnull().sum()
        for nan in range(len(null)):
            if null[nan] > 0:
                df.dropna(inplace=True)
                print(f'{null[nan]} Nan Values Droped!')
            if null[nan] == 0:
                print("No Nan Values Found:)")
    
    def drop_col(self, df, col):
        df.drop(col, axis=1, inplace=True)
    
    def merge(self, left, right, on):
        return pd.merge(left=left, right=right, on=on)
    
    def rename(self, df, dict_data):
        df.rename(dict_data,axis=1,inplace=True)
    
    def replace(self, df, col, rp, to_rp):
        df[col] = df[col].str.replace(rp, to_rp)
    
    def getActors_bollywood(self, data,  director = False,  actor_1 = False,  actor_2 = False, actor_3 = False, actor_4 = False):
        data = str(data).split('|')
        try:
            if director == True:
                return data[0]
        except:
            return 'unknown'
        try:
            if actor_1 == True:
                return data[1]
        except:
            return 'unknown'
        try:
            if actor_2 == True:
                return data[2]
        except:
            return 'unknown'
        try:
            if actor_3 == True:
                return data[3]
        except:
            return 'unknown'
        try:
            if actor_4 == True:
                return data[4]
        except:
            return 'unknown'
    
    def combine(self, df):
        return df['director_name'] + ' ' + df['actor_1_name'] + ' ' + df['actor_2_name'] + ' ' + df['actor_3_name'] + ' ' + df['actor_4_name'] + ' ' + df['genres']

In [844]:
bollywood_dataset = BOLLYWOOD_DATASET()

In [845]:
df_1989_actors = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/1950-1989/bollywood_text_1950-1989.csv', col=['actors', 'imdb_id'])
df_1989_actors.head()

     imdb_id                                             actors
0  tt0349122                                                NaN
1  tt0098168  Rakhee Gulzar|Jackie Shroff|Anil Kapoor|Dimple...
2  tt0122427  Sridevi|Sunny Deol|Rajinikanth|Anupam Kher|Sha...
3  tt0096896  Dharmendra|Vinod Khanna|Dimple Kapadia|Poonam ...
4  tt0233146  Jeetendra|Raj Babbar|Anita Raj|Govinda|Sonam|S...

In [846]:
df_1989_genres = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/1950-1989/bollywood_meta_1950-1989.csv', col=['genres', 'imdb_id', 'title'])
df_1989_genres.head()

     imdb_id       title                genres
0  tt0042184       Afsar        Comedy|Romance
1  tt0042207       Arzoo       Musical|Romance
2  tt0042225      Banwra                 Drama
3  tt0042233  Bawre Nain         Drama|Romance
4  tt0042380      Dastan  Drama|Family|Romance

In [847]:
bollywood_dataset.get_shape(df_1989_genres), bollywood_dataset.get_shape(df_1989_actors)

((2159, 3), (2128, 2))

In [848]:
bollywood_dataset.nanVal(df_1989_genres), bollywood_dataset.nanVal(df_1989_actors)

No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
13 Nan Values Droped!

(None, None)

In [849]:
df_1989_new = bollywood_dataset.merge(left=df_1989_genres, right=df_1989_actors, on=['imdb_id'])
bollywood_dataset.drop_col(df_1989_new, ['imdb_id'])
bollywood_dataset.rename(df_1989_new, {'title':'movie_title'})
bollywood_dataset.replace(df_1989_new, 'genres', '|', " ")
df_1989_new.head()
df_1989_new.head()

,movie_title,genres,actors
0,Afsar,Comedy Romance,Dev Anand|Suraiya|Ruma Guha Thakurta|Kanhaiyal...
1,Arzoo,Musical Romance,Kamini Kaushal|Dilip Kumar|Shashikala|Neelam|A...
2,Banwra,Drama,Raj Kapoor|Lalita Pawar|Nimmi|K.N. Singh|Hiral...
3,Bawre Nain,Drama Romance,Raj Kapoor|Geeta Bali|Vijayalaxmi|Jaswant|Pesi...
4,Dastan,Drama Family Romance,Suraiya|Raj Kapoor|Veena|Suresh|Al Nasir|Prati...

In [850]:
bollywood_dataset.nanVal(df_1989_new)

No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)

In [851]:
df_1989_new['actors'][0]

'Dev Anand|Suraiya|Ruma Guha Thakurta|Kanhaiyalal Chaturvedi|Rashid Khan|Manmohan Krishna|Mohan Segal|Krishan Dhawan|Anand Pal|'

In [852]:
df_1989_new['director_name'] = df_1989_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, director=True))
df_1989_new['actor_1_name'] = df_1989_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_1=True))
df_1989_new['actor_2_name'] = df_1989_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_2=True))
df_1989_new['actor_3_name'] = df_1989_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_3=True))
df_1989_new['actor_4_name'] = df_1989_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_4=True))
bollywood_dataset.drop_col(df_1989_new,'actors')
df_1989_new['combination'] = bollywood_dataset.combine(df_1989_new)
df_1989_new.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,actor_4_name,combination
0,Afsar,Comedy Romance,Dev Anand,Suraiya,Ruma Guha Thakurta,Kanhaiyalal Chaturvedi,Rashid Khan,Dev Anand Suraiya Ruma Guha Thakurta Kanhaiyal...
1,Arzoo,Musical Romance,Kamini Kaushal,Dilip Kumar,Shashikala,Neelam,Arif,Kamini Kaushal Dilip Kumar Shashikala Neelam A...
2,Banwra,Drama,Raj Kapoor,Lalita Pawar,Nimmi,K.N. Singh,Hiralal,Raj Kapoor Lalita Pawar Nimmi K.N. Singh Hiral...
3,Bawre Nain,Drama Romance,Raj Kapoor,Geeta Bali,Vijayalaxmi,Jaswant,Pesi Patel,Raj Kapoor Geeta Bali Vijayalaxmi Jaswant Pesi...
4,Dastan,Drama Family Romance,Suraiya,Raj Kapoor,Veena,Suresh,Al Nasir,Suraiya Raj Kapoor Veena Suresh Al Nasir Drama...

In [853]:
df_2009_genres = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/1990-2009/bollywood_meta_1990-2009.csv', col=['genres', 'imdb_id', 'title'])
df_2009_genres.head()

     imdb_id                        title              genres
0  tt0054098                Mughal-E-Azam   Drama|Romance|War
1  tt0096775                    Agneekaal  Action|Crime|Drama
2  tt0098461                    Thanedaar  Action|Crime|Drama
3  tt0098975  Aadhi Haqeeqat Aadha Fasana         Documentary
4  tt0098976                 Aaj Ka Arjun  Action|Crime|Drama

In [854]:
df_2009_actors = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/1990-2009/bollywood_text_1990-2009.csv', col=['actors', 'imdb_id'])
df_2009_actors.head()

     imdb_id                                             actors
0  tt1187043  Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...
1  tt1275863  Saif Ali Khan|Deepika Padukone|Rishi Kapoor|Ra...
2  tt1340838       Kangana Ranaut|Adhyayan Suman|Emraan Hashmi|
3  tt1252596  Ranbir Kapoor|Katrina Kaif|Darshan Jariwala|Sm...
4  tt1084972  Salman Khan|Ayesha Takia|Vinod Khanna|Govind N...

In [855]:
bollywood_dataset.get_shape(df_2009_genres), bollywood_dataset.get_shape(df_2009_actors)

((1535, 3), (1531, 2))

In [856]:
bollywood_dataset.nanVal(df_2009_actors), bollywood_dataset.nanVal(df_2009_genres)

No Nan Values Found:)
5 Nan Values Droped!
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)

(None, None)

In [857]:
df_2009_new = bollywood_dataset.merge(left=df_2009_genres, right=df_2009_actors, on=['imdb_id'])
bollywood_dataset.drop_col(df_2009_new, ['imdb_id'])
bollywood_dataset.rename(df_2009_new, {'title':'movie_title'})
bollywood_dataset.replace(df_2009_new, 'genres', '|', " ")
df_2009_new.head()
df_2009_new.head()

,movie_title,genres,actors
0,Mughal-E-Azam,Drama Romance War,Prithviraj Kapoor|Madhubala|Dilip Kumar|Durga ...
1,Agneekaal,Action Crime Drama,Masum Ali|Sadashiv Amrapurkar|Tinnu Anand|Raj ...
2,Thanedaar,Action Crime Drama,Jeetendra|Sanjay Dutt|Jaya Prada|Madhuri Dixit...
3,Aaj Ka Arjun,Action Crime Drama,Amitabh Bachchan|Jaya Prada|Radhika Sarathkuma...
4,Agneepath,Action Crime Drama,Amitabh Bachchan|Mithun Chakraborty|Madhavi|Ne...

In [858]:
df_2009_new['director_name'] = df_2009_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, director=True))
df_2009_new['actor_1_name'] = df_2009_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_1=True))
df_2009_new['actor_2_name'] = df_2009_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_2=True))
df_2009_new['actor_3_name'] = df_2009_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_3=True))
df_2009_new['actor_4_name'] = df_2009_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_4=True))
bollywood_dataset.drop_col(df_2009_new, 'actors')
df_2009_new['combination'] = bollywood_dataset.combine(df_2009_new)
df_2009_new.head()
df_2009_new.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,actor_4_name,combination
0,Mughal-E-Azam,Drama Romance War,Prithviraj Kapoor,Madhubala,Dilip Kumar,Durga Khote,Nigar Sultana,Prithviraj Kapoor Madhubala Dilip Kumar Durga ...
1,Agneekaal,Action Crime Drama,Masum Ali,Sadashiv Amrapurkar,Tinnu Anand,Raj Babbar,Leena Das,Masum Ali Sadashiv Amrapurkar Tinnu Anand Raj ...
2,Thanedaar,Action Crime Drama,Jeetendra,Sanjay Dutt,Jaya Prada,Madhuri Dixit,Kiran Kumar,Jeetendra Sanjay Dutt Jaya Prada Madhuri Dixit...
3,Aaj Ka Arjun,Action Crime Drama,Amitabh Bachchan,Jaya Prada,Radhika Sarathkumar,Suresh Oberoi,Kiran Kumar,Amitabh Bachchan Jaya Prada Radhika Sarathkuma...
4,Agneepath,Action Crime Drama,Amitabh Bachchan,Mithun Chakraborty,Madhavi,Neelam Kothari,Danny Denzongpa,Amitabh Bachchan Mithun Chakraborty Madhavi Ne...

In [859]:
df_2019_genres = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/2010-2019/bollywood_meta_2010-2019.csv', col=['genres', 'imdb_id', 'title'])
df_2019_genres.head()

     imdb_id                      title                   genres
0  tt0073707                     Sholay  Action|Adventure|Comedy
1  tt0246825               Om Dar-B-Dar                    Drama
2  tt0403935             Action Jackson          Action|Thriller
3  tt0443331            Milenge Milenge            Drama|Romance
4  tt0839742  Bhopal: A Prayer for Rain                    Drama

In [860]:
df_2019_actors = bollywood_dataset.load_dataset(path='../input/the-indian-movie-database/2010-2019/bollywood_text_2010-2019.csv', col=['actors', 'imdb_id'])
df_2019_actors.head()

     imdb_id                                             actors
0  tt5013008  Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...
1  tt8291224  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
2  tt9472208  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
3  tt6986710  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
4  tt6028796  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...

In [861]:
bollywood_dataset.get_shape(df_2019_genres), bollywood_dataset.get_shape(df_2019_actors)

((929, 3), (919, 2))

In [862]:
bollywood_dataset.nanVal(df_2019_genres), bollywood_dataset.nanVal(df_2019_actors)

No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
2 Nan Values Droped!

(None, None)

In [863]:
df_2019_new = bollywood_dataset.merge(left=df_2019_genres, right=df_2019_actors, on=['imdb_id'])
bollywood_dataset.drop_col(df_2019_new, ['imdb_id'])
bollywood_dataset.rename(df_2019_new, {'title':'movie_title'})
bollywood_dataset.replace(df_2019_new, 'genres', '|', " ")
df_2019_new.head()
df_2019_new.head()

,movie_title,genres,actors
0,Sholay,Action Adventure Comedy,Sanjeev Kumar|Dharmendra|Amitabh Bachchan|Amja...
1,Om Dar-B-Dar,Drama,Gopi Desai|Manish Gupta|Anita Kanwar|Aditya La...
2,Action Jackson,Action Thriller,Prabhas|Shahid Kapoor|Ajay Devgn|Sonakshi Sinh...
3,Milenge Milenge,Drama Romance,Kareena Kapoor|Shahid Kapoor|Aarti Chhabria|De...
4,Bhopal: A Prayer for Rain,Drama,Mischa Barton|Martin Sheen|Kal Penn|Lisa Dwan|...

In [864]:
df_2019_new['director_name'] = df_2019_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, director=True))
df_2019_new['actor_1_name'] = df_2019_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_1=True))
df_2019_new['actor_2_name'] = df_2019_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_2=True))
df_2019_new['actor_3_name'] = df_2019_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_3=True))
df_2019_new['actor_4_name'] = df_2019_new['actors'].apply(lambda x: bollywood_dataset.getActors_bollywood(x, actor_4=True))
bollywood_dataset.drop_col(df_2019_new, 'actors')
df_2019_new['combination'] = bollywood_dataset.combine(df_2019_new)
df_2019_new.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,actor_4_name,combination
0,Sholay,Action Adventure Comedy,Sanjeev Kumar,Dharmendra,Amitabh Bachchan,Amjad Khan,Hema Malini,Sanjeev Kumar Dharmendra Amitabh Bachchan Amja...
1,Om Dar-B-Dar,Drama,Gopi Desai,Manish Gupta,Anita Kanwar,Aditya Lakhia,Lakshminarayan Shastri,Gopi Desai Manish Gupta Anita Kanwar Aditya La...
2,Action Jackson,Action Thriller,Prabhas,Shahid Kapoor,Ajay Devgn,Sonakshi Sinha,Prabhu Deva,Prabhas Shahid Kapoor Ajay Devgn Sonakshi Sinh...
3,Milenge Milenge,Drama Romance,Kareena Kapoor,Shahid Kapoor,Aarti Chhabria,Delnaaz Irani,Satish Shah,Kareena Kapoor Shahid Kapoor Aarti Chhabria De...
4,Bhopal: A Prayer for Rain,Drama,Mischa Barton,Martin Sheen,Kal Penn,Lisa Dwan,Tannishtha Chatterjee,Mischa Barton Martin Sheen Kal Penn Lisa Dwan ...

In [868]:
bollywood_dataset.get_shape(old_df), bollywood_dataset.get_shape(df_1989_new), bollywood_dataset.get_shape(df_2009_new), bollywood_dataset.get_shape(df_2019_new)

((6249, 8), (2146, 8), (1530, 8), (914, 8))

In [903]:
final_df = pd.concat([old_df, df_1989_new, df_2009_new, df_2019_new], ignore_index=False)
final_df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,combination,actor_4_name
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...,unknown
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...,unknown
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...,unknown
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,unknown
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...,unknown

In [904]:
bollywood_dataset.get_shape(final_df)

(10839, 8)

In [905]:
bollywood_dataset.nanVal(final_df)

No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)
No Nan Values Found:)

In [906]:
final_df.to_csv('main_hollywood_bollyWood_dataset.csv', index=False)

In [908]:
bollywood_dataset.load_dataset(path='./main_hollywood_bollyWood_dataset.csv', col=['movie_title'])

                                             movie_title
0                                                 avatar
1               pirates of the caribbean: at world's end
2                                                spectre
3                                  the dark knight rises
4      star wars: episode vii - the force awakens    ...
...                                                  ...
10834                                           22 Yards
10835                                   PM Narendra Modi
10836                            Bachche Kachche Sachche
10837                                 Pati Patni Aur Woh
10838                                          Risknamaa

[10839 rows x 1 columns]